# Jekyll configuration
name: InfernoRDN
description: InfernoRDN can perform various downstream data analysis, data reduction, and data comparison tasks including normalization, hypothesis testing, clustering, and heatmap generation.
url: https://pnnl-comp-mass-spec.github.io/InfernoRDN/

# Google Analytics
google_analytics: G-LXXKP1N66C
